/// Flutter icons MyFitnessBuddy
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFitnessBuddy
///      fonts:
///       - asset: fonts/MyFitnessBuddy.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFitnessBuddy {
  MyFitnessBuddy._();

  static const _kFontFam = 'MyFitnessBuddy';

  static const IconData gym = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData meal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData journal = const IconData(0xe803, fontFamily: _kFontFam);
}
